### ISSUE TITLE
npm v1.1.0 missing important fix #6

### ISSUE THREAD

**Issue by ahmader** [jusx/node-wufoo#11]
When installing wufoo via npm it shows different hashes, which is behind the v1.1.0 tag commit.

```
$ npm install wufoo@1.1.0
$ cat node_modules/wufoo/package.json | grep gitHead
       "gitHead": "**64f5d5b9a8d955f548c0ad369bd977b6c2c2f783**",
```

While cloning the repo

```
$ git clone https://github.com/jusx/node-wufoo.git node-wufoo && cd node-wufoo
$ git checkout v1.1.0
       HEAD is now at bc1a4c2... Merge pull request #6 from jusx/bugfix-request-querystring
$ git rev-parse HEAD
       **bc1a4c27f16b5bca0fd50febc2ebc5e4babe0998**
```

I have been straggling  with this issue for every install of v1.1.0 the reason I am still using it is because v1.2.0 require node >= 8.0.0

Any suggestion how to fix this ?
I am thinking of creating a new tag with version v1.1.1 from that specific commit.

**Comment by ahmader** [comment]
My current workaround is to install it this way

```
$ npm install --save jusx/node-wufoo#v1.1.0
```

Maybe to create a new branch for v1.1.x to keep support for older node ?

**Comment by jusx** [comment]
@ahmader Yup. I like your proposal. I'll work on pushing up a patch to npm this weekend.

**Comment by jusx** [comment]
@ahmader I've created a branch for the patch and published a new patched version 1.1.1 to npmjs. 

` npm install wufoo@1.1.1` should now give you the version with the right fixes and corresponds with the tag in v1.1.1 -- `npm install wufoo` should install the latest which is 1.2.0

Let me know if this is working for you.

**Comment by ahmader** [comment]
@jusx Thanks I will test it and report back.

**Comment by ahmader** [comment]
@jusx That worked as expected. 

Thanks I will close the issue.
